# Generated by Django 3.2.3 on 2023-07-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
